### ISSUE TITLE
Leader's teams

### ISSUE THREAD

**Issue by Liczi** [fingo/urlopia#18]
There is an issue with employees, who are assigned to multiple teams and are in Leaders Team. It causes some teams to have multiple leaders. 
![s1](https://cloud.githubusercontent.com/assets/17939321/21098583/3632184e-c06a-11e6-80be-a4fd21876780.PNG)
![s2](https://cloud.githubusercontent.com/assets/17939321/21098584/36339ab6-c06a-11e6-9367-56622ce2785e.PNG)

**Comment by puninup** [comment]
Its known issue, and I think know how to solve it :)

**Comment by puninup** [comment]
I fixed this issue from the logical site, but I don't know how to show it for the user. 
Maybe we should mark the exact team instead of user name? But it causes much of code changes and I think it will be less intuitive.

**Comment by Liczi** [comment]
proposed solution is to make name **and** team name in which the person is leader bold.
