### ISSUE TITLE
Delete cancelled requests

### ISSUE THREAD

**Issue by Liczi** [fingo/urlopia#25]
When user cancells his unaccepted holiday request it should be also deleted from the database.

**Comment by Liczi** [comment]
delete from database

**Comment by puninup** [comment]
what with acceptances? should we send an e-mail message that the request was a mistake? or just delete and forget?

**Comment by puninup** [comment]
Canceled request should have status `CANCELED` - it doesn't matter if it had been accepted or not. Modification rejected.
