### ISSUE TITLE
Refactor confirmation modal

### ISSUE THREAD

**Issue by Liczi** [fingo/urlopia#29]
Refactor confirmation modal to use **one service** and **one template** HTML (`confirmation_dialog.html`). The template will contain "Are you sure" and message body provided by service method, which will return a callback on modal dismissing with information about user's choice. E.g. : 
`ConfirmationService.showConfirmationDialog(message, callback_ok, callback_cancel)`
where `message` could use `$translate.instant` function and callback functions defined by user.

**Comment by Liczi** [comment]
## Sub-issue
Add confirmation dialog on deleting a holiday in holidays view

**Comment by Liczi** [comment]
issue addresed on [refactoring_modal](https://github.com/fingo/urlopia/tree/refactoring_modal) branch

**Comment by puninup** [comment]
`refactoring_modal` branch has been removed.
