### ISSUE TITLE
What to do when employee work time is changing? - Report checking before generate

### ISSUE THREAD

**Issue by Liczi** [fingo/urlopia#34]
If employee changes his work time and he was using the application for a while (meaning he has some requests and vacation history) his history needs to be split into sections grouped by his work time or the previous history should be flagged as deprecated.

**Comment by puninup** [comment]
I think it's fixed in current version...
But I don't know what to do with reports.

**Comment by puninup** [comment]
Before generate the report we should check if employee's work-time has changed during the year. If the work-time for a while is smaller than full-time the report should be shown with hours (like for non full-time employees).

**Comment by puninup** [comment]
Issue seems to be fixed at now. I'm closing it.
