### ISSUE TITLE
E-mail for leader if someone/admin is canceling the request

### ISSUE THREAD

**Issue by Liczi** [fingo/urlopia#36]
Add an e-mail response which will contain confirmation of the request submission (after succesful submission via e-mail)

**Comment by puninup** [comment]
Do we need it? At now we know that no response from urlopia means "everything is fine".

**Comment by puninup** [comment]
Instead of the confirmation e-mail, the leader should get information when any request is canceled.

**Comment by puninup** [comment]
done
