### ISSUE TITLE
missing english translations

### ISSUE THREAD

**Issue by prestidigitator84** [fingo/urlopia#40]
![translation 1](https://cloud.githubusercontent.com/assets/24713143/21419853/7d98488a-c82a-11e6-9b03-e311e18556cf.png)
![translation 2](https://cloud.githubusercontent.com/assets/24713143/21419854/7dad6670-c82a-11e6-8fc5-9dbe4218e571.png)
![translation 3](https://cloud.githubusercontent.com/assets/24713143/21419855/7dbd0e86-c82a-11e6-9db9-3bd2ae736b8c.png)

**Comment by Liczi** [comment]
Bug fix track
In english translations file:
![image](https://cloud.githubusercontent.com/assets/17939321/21424932/5054be00-c846-11e6-81fa-3e6315a8f587.png)
