### ISSUE TITLE
Type Double rounding issues

### ISSUE THREAD

**Issue by Liczi** [fingo/urlopia#46]
In database there are following records:
![image](https://cloud.githubusercontent.com/assets/17939321/21500139/1fab0238-cc3c-11e6-88a1-4a699269a7e8.png)

There should be restriction to write only with precision 0.01 hour and make sure that approximation will not  affect correctness of the record. 

Probably the weak spot is `DurationCalculator` class which uses Double to calculate hours, and every service which is using `HistoryService`.

Having the knowledge of 2.0 - 1.1 is equal to 0.8999999999999999 we have to ensure data correctness in database or before inserting to database

**Comment by Liczi** [comment]
database change in https://github.com/fingo/urlopia/pull/48/commits/54b5711d82081a3abf045a62d6566277af6c5e55

**Comment by puninup** [comment]
DurationCalculator calculate only number of workdays, so it's probably not the cause.

**Comment by Liczi** [comment]
but There is also multiplication by work time and causes problems

27.12.2016 6:13 PM "Tomasz Urbas" <notifications@github.com> napisał(a):
