### ISSUE TITLE
Bug canceling request

### ISSUE THREAD

**Issue by Liczi** [fingo/urlopia#6]
When administrator cancels a request it is not cancelled, but the user is granted a request duration days to pool

**Comment by puninup** [comment]
can you show all the steps taken, when this issue occurs? I can't make it. 
But I see other problems:  
- when I try to refuse the worker request by admin then that worker see that the request was refused by leader... 
- when admin cancel worker's request then history says that it was worker
![admin canceling](https://cloud.githubusercontent.com/assets/9154976/20968563/45fe07c6-bc85-11e6-987d-61330484fa25.png)

**Comment by Liczi** [comment]
resolved in https://github.com/fingo/urlopia/pull/16/commits/440642b2298c087587335383fe6d17f30f532976

**Comment by Liczi** [comment]
resolved in https://github.com/fingo/urlopia/pull/16/commits/440642b2298c087587335383fe6d17f30f532976
