### ISSUE TITLE
Add calendar view with absence/holiday schedule for whole team

### ISSUE THREAD

**Issue by rafalgradziel** [fingo/urlopia#65]
On Fingo Calendar we have a view for all holidays/delegations/sick leave all together - for whole team.
If we should add vacation schedule via Urlopia - please add calendar view, where we can see team members' requests in a month view (it would be easy to schedule vacations or revoke overlapping requests when looking on graphical representation of the requests)

**Comment by puninup** [comment]
At now Urlopia have calendar view for 2 next weeks which contains information about all teammates vacations. If it is not enough - please, create new issue.
