### ISSUE TITLE
Email with OK does not accept the request

### ISSUE THREAD

**Issue by rafalgradziel** [fingo/urlopia#76]
**Steps to reproduce**
1. As TeamLeader, get email from Urlopia about your team's employee vacation request
2. Email says "Żeby zaakceptować wniosek przejdź pod link http://urlopia.fingo.info lub odpowiedz "OK" na tą wiadomość."
3. Hit "Reply" in email app and add "OK" on the top of the message

**Expected behaviour**
Request is accepted and you can check this status on WWW

**Actual behaviour**
Request is not accepted, with no email confirming failure (i.e. "Email format was not recognized, please go to website to finish your action")

**Attached files**
1. "Prosba o urlop 111.msg" - email request as received from Urlopia
2. "ODP Prosba o urlop 111.msg" - reply via email to Urlopia
3. "odp prosba o urlop 111.png - screenshot

[Prosba o urlop 111.zip](https://github.com/fingo/urlopia/files/863957/Prosba.o.urlop.111.zip)
![odp prosba o urlop 111](https://cloud.githubusercontent.com/assets/4716102/24237313/0df97f30-0fa6-11e7-96a7-cb97c321ed2c.png)

**Comment by puninup** [comment]
Does this problem still occur?

**Comment by puninup** [comment]
I assume it works fine now.
